### ISSUE TITLE
Error in decimallookupv2.js file

### ISSUE THREAD

**Issue by sugandha-tiwari** [cerlane/posit-javascript#2]
Hi

While using Decimal to Posit Lookup Table Generator I came across one issue. For converting decimal value 0.00390625 to posit, the result we got through converter was Posit<32,3> = 00011000000000000000000000000000 . But I think that 00100000000000000000000000000000 is a more accurate representation for the given decimal value. After going through the code we found that if line no. 171 is updated to "if (temp2>=useed)"  (in decimallookupv2.js file) it will give more accurate representation. Please tell me if I am correct or going wrong somewhere.
I have attached screen shot for the updated result that I got.
![posit error](https://user-images.githubusercontent.com/33784836/38549329-67158a7e-3cd1-11e8-85c8-7611713b7902.png)

**Comment by cerlane** [comment]
Yes, you are right! Thanks! I will fix the bug.

**Comment by cerlane** [comment]
Done. Thanks again!
