### ISSUE TITLE
Bug for negative numbers in Decimal to Posit

### ISSUE THREAD

**Issue by mightymercado** [cerlane/posit-javascript#3]
Try -0.5 in decimal to Posit, then for Posit<6,0>, you get -11100 or 111100, which is -0.25. My posit implementation returns 111000, which is the right answer.

I discovered while building a unit test in my python implementation that uses this javascript code to counter check if the conversion from float to Posit is correct.

Here is my implementation: https://github.com/mightymercado/PySigmoid (look into PySigmoid/Posit.py)

**Comment by cerlane** [comment]
The widget is returning -11000 as the binary, which is the correct answer.

**Comment by mightymercado** [comment]
The site does, but the code in github doesnt.
![image](https://user-images.githubusercontent.com/11026445/40233526-f0fb8e9c-5ad5-11e8-8f27-0b517319ab53.png)

**Comment by waldyrious** [comment]
By the way, if the GitHub Pages option is turned on in [the repo settings](https://github.com/cerlane/posit-javascript/settings), the code will be made available live at http://cerlane.github.io/posit-javascript/lookup.html, resulting in a page that will look [like this](https://rawgit.com/cerlane/posit-javascript/master/lookup.html) (and [this](https://rawgit.com/cerlane/posit-javascript/master/plookup.html) for `plookup.html`).
